[package]
name = "tt-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
santiago = "*"
odbc-api = "*"
# anyhow = "*"
csv = "*"
tokio = { version = "*", features=["full"] }
crossterm = { version = "*", features=["event-stream"] }
futures = "*"
futures-timer = "*"
chrono = "*"
rusqlite = { version = "0.29.0", features = ["bundled", "modern_sqlite"] }
serde = { version = "1.0"}
error = "0.1.9"
tracing = "0.1.37"
bytes = "1.5.0"

[dev-dependencies]
serde_derive = "1.0"
