[package]
name = "tt-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
santiago = "*"
sqlite = "*"
odbc-api = "*"
# anyhow = "*"
csv = "*"

tokio = { version = "*", features=["full"] }
crossterm = { version = "*", features=["event-stream"] }
futures = "*"
futures-timer = "*"
chrono = "*"
